"""Added bio column

Revision ID: f85c6e444907
Revises: a0d284b8d0be
Create Date: 2024-05-20 18:33:17.377015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f85c6e444907'
down_revision = 'a0d284b8d0be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subheading', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['title'])

    with op.batch_alter_table('thread', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['title'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bio', sa.Text(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('bio')

    with op.batch_alter_table('thread', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('subheading', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
